In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1=pd.read_csv("Downloads/anime-recommendations-database/anime.csv")

In [3]:
df2=pd.read_csv("Downloads/anime-recommendations-database/rating.csv")

In [4]:
df2=df2[df2['rating']!=-1]
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6337241 entries, 47 to 7813736
Data columns (total 3 columns):
user_id     int64
anime_id    int64
rating      int64
dtypes: int64(3)
memory usage: 193.4 MB

In [5]:
df2=df2.iloc[0:6337240,:]
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6337240 entries, 47 to 7813735
Data columns (total 3 columns):
user_id     int64
anime_id    int64
rating      int64
dtypes: int64(3)
memory usage: 193.4 MB

In [6]:
df1.drop('rating',axis=1,inplace=True)

In [7]:
df=df1.merge(df2,on='anime_id')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6337238 entries, 0 to 6337237
Data columns (total 8 columns):
anime_id    int64
name        object
genre       object
type        object
episodes    object
members     int64
user_id     int64
rating      int64
dtypes: int64(4), object(4)
memory usage: 435.1+ MB

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6337238 entries, 0 to 6337237
Data columns (total 8 columns):
anime_id    int64
name        object
genre       object
type        object
episodes    object
members     int64
user_id     int64
rating      int64
dtypes: int64(4), object(4)
memory usage: 435.1+ MB

In [10]:
anime_table=df.pivot_table(index='user_id',columns='name',values='rating')
anime_table.head()

name,&quot;0&quot;,"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,&quot;Eiji&quot;,.hack//G.U. Returner,.hack//G.U. Trilogy,.hack//G.U. Trilogy: Parody Mode,.hack//Gift,...,lilac (bombs Jun Togawa),makemagic,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,◯
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
anime_table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69600 entries, 1 to 73516
Columns: 9926 entries, &quot;0&quot; to ◯
dtypes: float64(9926)
memory usage: 5.1 GB

In [12]:
rating=pd.DataFrame(df.groupby('name')['rating'].mean())
rating.head()

                                                      rating
name
&quot;0&quot;                                       4.764706
&quot;Aesop&quot; no Ohanashi yori: Ushi to Kae...  1.000000
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hats...  7.343307
&quot;Bungaku Shoujo&quot; Memoire                  7.744713
&quot;Bungaku Shoujo&quot; Movie                    7.840154

In [13]:
rating['num of rating']=pd.DataFrame(df.groupby('name')['rating'].count())
rating.head()

                                                      rating  num of rating
name
&quot;0&quot;                                       4.764706             17
&quot;Aesop&quot; no Ohanashi yori: Ushi to Kae...  1.000000              1
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hats...  7.343307            635
&quot;Bungaku Shoujo&quot; Memoire                  7.744713            662
&quot;Bungaku Shoujo&quot; Movie                    7.840154           1295

In [14]:
rating.sort_values('num of rating',ascending=False).head()

                                   rating  num of rating
name
Death Note                       8.834629          34226
Sword Art Online                 8.140213          26310
Shingeki no Kyojin               8.725741          25290
Code Geass: Hangyaku no Lelouch  8.927796          24126
Angel Beats!                     8.549714          23565

In [15]:
shingeki_rating=anime_table['Shingeki no Kyojin']
shingeki_rating.head()

user_id
1     NaN
2     NaN
3    10.0
5     NaN
7     NaN
Name: Shingeki no Kyojin, dtype: float64

In [16]:
similar_to_shingeki=anime_table.corrwith(shingeki_rating)
similar_to_shingeki.head()

D:\conda\anaconda\lib\site-packages\numpy\lib\function_base.py:2392: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
D:\conda\anaconda\lib\site-packages\numpy\lib\function_base.py:2326: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

name
&quot;0&quot;                                                       0.298825
&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu         NaN
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi                 0.208909
&quot;Bungaku Shoujo&quot; Memoire                                  0.170715
&quot;Bungaku Shoujo&quot; Movie                                    0.222992
dtype: float64

In [17]:
corr_shingeki=pd.DataFrame(similar_to_shingeki,columns=['correlation'])
corr_shingeki.dropna(inplace=True)
corr_shingeki.head()

                                                    correlation
name
&quot;0&quot;                                          0.298825
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hats...     0.208909
&quot;Bungaku Shoujo&quot; Memoire                     0.170715
&quot;Bungaku Shoujo&quot; Movie                       0.222992
&quot;Eiji&quot;                                       0.313468

In [18]:
corr_shingeki.sort_values('correlation',ascending=False).head()

                                               correlation
name
Majuu Sensen                                           1.0
New Hal &amp; Bons                                     1.0
Micro Teukgongdae Diatron 5                            1.0
Super Majingga 3                                       1.0
Kero Kero Keroppi no Boku-tachi no Takaramono          1.0

In [19]:
corr_shingeki=corr_shingeki.join(rating['num of rating'])
corr_shingeki.head()

                                                    correlation  num of rating
name
&quot;0&quot;                                          0.298825             17
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hats...     0.208909            635
&quot;Bungaku Shoujo&quot; Memoire                     0.170715            662
&quot;Bungaku Shoujo&quot; Movie                       0.222992           1295
&quot;Eiji&quot;                                       0.313468             14

In [21]:
corr_shingeki[corr_shingeki['num of rating']>100].sort_values('correlation',ascending=False)

                                                    correlation  num of rating
name
Shingeki no Kyojin                                     1.000000          25290
Kyoushirou to Towa no Sora Specials                    0.658898            110
Okusama wa Mahou Shoujo                                0.651384            141
Shin Koihime†Musou: Live Revolution                    0.585598            111
Shingeki no Kyojin Movie 2: Jiyuu no Tsubasa           0.571831            169
Shingeki no Kyojin OVA                                 0.564776           2742
Shingeki no Kyojin: Kuinaki Sentaku                    0.558702           1942
Eden&#039;s Bowy                                       0.546005            117
Inazuma Eleven Go: Kyuukyoku no Kizuna Gryphon         0.544113            115
Kishin Taisen Gigantic Formula                         0.530277            122
Final Fantasy VII: Advent Children - Venice Fil...     0.523416            206
Mokei Senshi Gunpla Builders Beginning G               0.506507            102
I&#039;&#039;s Pure Bonus                              0.504061            218
Je T&#039;aime                                         0.502979            134
11-nin Iru!                                            0.498869            124
Penguin Musume♥Heart Special                           0.491401            102
Hyakujuu-Ou GoLion                                     0.490654            235
Tide-Line Blue                                         0.489832            133
Pokemon 3D Adventure 2: Pikachu no Kaitei Daibo...     0.487903            133
Hokuto no Ken Zero: Kenshirou Den                      0.484904            130
Kinnikuman II Sei                                      0.483550            205
Omae Umasou da na                                      0.481019            146
Slam Dunk: Hoero Basketman-damashii! Hanamichi ...     0.480499            302
Princess Tutu Recaps                                   0.478634            130
SKET Dance OVA                                         0.478148            415
Anime 80-nichikan Sekai Isshuu                         0.476451            108
Ai no Wakakusa Monogatari                              0.475748            109
Kurokami: Intermission                                 0.474407            142
Konjiki no Gash Bell!!: 101 Banme no Mamono            0.472648            160
Flanders no Inu (Movie)                                0.471066            134
...                                                         ...            ...
Naisho no Tsubomi                                     -0.093811            190
Shintaisou: Kari                                      -0.095023            118
Daicon Opening Animations                             -0.095564            202
Kumo no You ni Kaze no You ni                         -0.096997            106
Bannou Bunka Neko-Musume (1998)                       -0.099381            119
Takamiya Nasuno Desu!: Teekyuu Spin-off               -0.099590            182
Galaxy Angel 4                                        -0.102289            163
Lupin III: Part III                                   -0.102861            136
Buttobi!! CPU                                         -0.105125            163
Chikyuu Bouei Kigyou Dai-Guard                        -0.107131            134
Yojouhan Shinwa Taikei                                -0.108563           1837
Dirty Pair: The Movie                                 -0.109987            101
Akihabara Dennou-gumi                                 -0.114235            108
Tenshi no Drop                                        -0.118938            162
Inaka Isha                                            -0.120323            318
The Cockpit                                           -0.123548            145
Teekyuu 5                                             -0.124303            167
Piano                                                 -0.126971            160
Sexy Commando Gaiden: Sugoiyo!! Masaru-san            -0.127129            111
Lupin III: Dead or Alive                              -0.128234            147
Bannou Bunka Neko-Musume                              -0.138425            215
Sakura Taisen: Ouka Kenran                            -0.145513            107
Choboraunyopomi Gekijou Dai Ni Maku Ai Mai Mii:...    -0.146584            177
Mazinger Z                                            -0.149910            126
Teekyuu 6                                             -0.165377            129
Nasu: Andalusia no Natsu                              -0.169509            133
Teekyuu 7                                             -0.192488            112
Natsuyasumi.                                          -0.198707            107
Kagaku Ninja-tai Gatchaman                            -0.210966            113
Lupin III: Fuuma Ichizoku no Inbou                    -0.211491            128

[4129 rows x 2 columns]